---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.0.0
    hooks:
      - id: trailing-whitespace
        files: \.(js|json|rb|md|py|sh|txt|xml|yaml|yml)$
      - id: check-xml
      - id: check-case-conflict
      - id: end-of-file-fixer
